name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
#  sdk: '>=2.19.0-255.2.beta <3.0.0'
   sdk: '>=2.18.5 <3.0.0'

dependencies:
  args: ^2.0.0
  bezier: ^1.2.0
  build_runner: ^2.3.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.3
  quiver: ^3.1.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  vector_math: ^2.1.4
  sqlite3: ^1.7.0
  tuple: ^2.0.1
  intl: ^0.17.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
